"""Embed the offline WebUI in firmware. Run after editing webui/index.html."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'BendeRadio/webui/index.html'
TARGET = ROOT / 'BendeRadio/WebUiPage.h'

def build():
    page = SOURCE.read_text(encoding='utf-8')
    if ')BENDERUI"' in page:
        raise ValueError('Raw string delimiter occurs in HTML')
    TARGET.write_text('// Generated by agent-tools/build_webui.py; edit webui/index.html.\n'
                      '#pragma once\n#include <Arduino.h>\n'
                      'static const char kWebUiPage[] PROGMEM = R"BENDERUI(' + page + ')BENDERUI";\n',
                      encoding='utf-8', newline='\n')
    print(f'WebUI: {len(page.encode("utf-8"))} bytes')

if __name__ == '__main__':
    build()
