"""Render installed Piper/RVC voice once, then embed PCM24k in firmware.

No LLM, network requests, listener, microphone or live server changes.
Reuses existing WAVs unless --render is specified (keeps the approved takes).
"""
from pathlib import Path
import argparse
import hashlib
import json
import sys
import wave

ROOT = Path(__file__).resolve().parents[1]
SERVER = ROOT / 'BendeRadio/examples/BenderRealtime/local_server'
OUT = ROOT / 'artifacts/wake-replies'
PHRASES = (
    ('neutral_1', 'Кажи.'), ('neutral_2', 'Слухаю.'),
    ('warm_1', 'Так, я тут.'), ('warm_2', 'Що там у тебе?'),
    ('sarcastic_1', 'Знову ти?'), ('sarcastic_2', 'Ну, здивуй мене.'),
    ('rough_1', 'Ну, чого?'), ('rough_2', 'Кажи вже.'),
    ('curious_1', 'Що там?'), ('curious_2', 'Що цікавого?'),
    ('profane_1', 'Що, бля, знову?'), ('profane_2', 'Бля, ну кажи.'),
)
RATE = 24000


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--render', action='store_true')
    args = parser.parse_args()
    OUT.mkdir(parents=True, exist_ok=True)
    if args.render:
        sys.path.insert(0, str(SERVER))
        import server as s
        from preview_delivery import stop_worker, write_wav
        from ukrainian_word_stress import Disambiguation, Stressifier, StressSymbol
        assert s.VOICE_ONNX.is_file() and s.VOICE_JSON.is_file(), 'Installed Piper required'
        ok, reason = s.rvc_convert.ready()
        assert ok, reason
        s.load_stress_words()
        s._uk_stress = Stressifier(stress_symbol=StressSymbol.CombiningAcuteAccent,
                                  on_ambiguity='skip', disambiguation=Disambiguation.Dictionary)
        s.piper_voice = s.PiperVoice.load(str(s.VOICE_ONNX))
        s.piper_syn = s.SynthesisConfig(speaker_id=s.PIPER_SPEAKER, length_scale=s.PIPER_LENGTH,
                                       noise_scale=0.62, noise_w_scale=0.80)
        logs = []
        s.log = lambda text: (logs.append(text), print(text, flush=True))
        try:
            for name, text in PHRASES:
                print('Rendering', name, text, flush=True)
                logs.clear()
                pcm = s.synth(text)
                assert 'RVC ok' in logs and not any('RVC fail' in line for line in logs), name
                write_wav(OUT / (name + '.wav'), pcm, RATE)
        finally:
            stop_worker(s.rvc_convert._proc)
            s.rvc_convert._proc = None

    header = ['// Generated by agent-tools/build_wake_replies.py; PCM16 LE, 24 kHz mono.',
              '#pragma once', '#include <cstddef>', '#include <cstdint>',
              'namespace WakeReplyAudio {',
              'struct Clip { const uint8_t* data; size_t bytes; };']
    manifest, audition, total = [], [], 0
    for name, text in PHRASES:
        path = OUT / (name + '.wav')
        with wave.open(str(path), 'rb') as wav:
            assert (wav.getnchannels(), wav.getsampwidth(), wav.getframerate()) == (1, 2, RATE)
            pcm = wav.readframes(wav.getnframes())
        assert 0 < len(pcm) <= RATE * 2 * 3, (name, 'cue must be shorter than 3 seconds')
        assert len(pcm) % 2 == 0
        total += len(pcm)
        header.append(f'alignas(4) static const uint8_t {name}[] = {{')
        header.extend(','.join(str(v) for v in pcm[i:i+32]) + ',' for i in range(0, len(pcm), 32))
        header.append('};')
        manifest.append(dict(name=name, text=text, bytes=len(pcm), duration_ms=len(pcm)*500//RATE,
                             sha256=hashlib.sha256(pcm).hexdigest()))
        audition.append(pcm)
    assert total < 1000000, 'Keep flash margin for firmware'
    header.append('static const Clip clips[] = {')
    header.extend(f'{{{name}, sizeof({name})}},' for name, _ in PHRASES)
    header.extend(['};', 'constexpr size_t count = sizeof(clips)/sizeof(clips[0]);', '}'])
    (ROOT / 'BendeRadio/WakeReplyAudio.h').write_text('\n'.join(header)+'\n', encoding='utf-8')
    (OUT / 'manifest.json').write_text(json.dumps(dict(rate=RATE, bytes=total, clips=manifest),
                                                indent=2, ensure_ascii=False)+'\n', encoding='utf-8')
    with wave.open(str(OUT / 'all-replies.wav'), 'wb') as wav:
        wav.setparams((1, 2, RATE, 0, 'NONE', 'not compressed'))
        wav.writeframes(bytes(RATE).join(audition))
    print('Embedded', len(PHRASES), 'clips;', total, 'bytes', flush=True)


if __name__ == '__main__':
    main()
