"""Export the pinned experimental model and exact DSP coefficients (no recordings)."""
import hashlib
import json
from pathlib import Path
import numpy as np
from scipy.signal import firwin
from wake_training_audio import MEL, WINDOW

ROOT = Path(__file__).resolve().parents[1]
RUN = ROOT / 'artifacts/wake-training/prototype-v7-finetune'
DEST = ROOT / 'BendeRadio'

def array(name, values, dtype='float'):
    flat = np.asarray(values).ravel()
    vals = [f'{float(v):.9e}f' if dtype == 'float' else str(int(v)) for v in flat]
    return f'alignas(16) static const {dtype} {name}[] = {{\n' + '\n'.join(
        '    ' + ','.join(vals[i:i+12]) + ',' for i in range(0, len(vals), 12)) + '\n};\n'

def main():
    config = json.loads((RUN/'model.json').read_text(encoding='utf-8'))
    body = (RUN/'bender.int8.tflite').read_bytes()
    assert hashlib.sha256(body).hexdigest() == config['sha256']
    assert config['input_shape'] == [1,238,40,1] and config['threshold'] == .25
    # scipy resample_poly(up=2, down=3): 61-tap Kaiser FIR, DC gain=2.
    fir = (firwin(61, 1/3, window=('kaiser',5.0)).astype(np.float32)*2)
    # Sparse mel triangles, exactly the training matrix.
    starts=[]; lengths=[]; weights=[]
    for i in range(40):
        indices=np.flatnonzero(MEL[:,i]); starts.append(indices[0]); lengths.append(len(indices))
        weights.extend(MEL[indices,i])
    dsp = '// Generated by agent-tools/export_wake_runtime.py; do not edit.\n#pragma once\n#include <cstdint>\nnamespace WakeDspData {\n'
    dsp += array('window',WINDOW)+array('fir',fir)
    dsp += array('melStart',starts,'uint16_t')+array('melLength',lengths,'uint16_t')+array('melWeight',weights)
    dsp += array('twiddle',np.stack([np.cos(-2*np.pi*np.arange(256)/512),np.sin(-2*np.pi*np.arange(256)/512)],axis=1))+'}\n'
    (DEST/'WakeDspData.h').write_text(dsp,encoding='utf-8')
    model = '// Generated from prototype-v7-finetune. Experimental, diagnostic only.\n#pragma once\n#include <cstdint>\nnamespace WakeModelData {\n'
    model += f'constexpr char sha256[] = "{config["sha256"]}";\nconstexpr float threshold = {config["threshold"]}f;\n'
    model += f'constexpr float inputScale = {config["input_quantization"][0]:.12g}f;\nconstexpr int inputZero = {config["input_quantization"][1]};\n'
    model += array('model',list(body),'uint8_t')+'}\n'
    (DEST/'WakeModelData.h').write_text(model,encoding='utf-8')
    print('Exported',len(body),'model bytes and DSP coefficients:',config['sha256'])

if __name__ == '__main__': main()
